/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import java.awt.Color;

/**
 *
 * @author Smart Solution
 */
public class TLogin extends javax.swing.JFrame {

    /**
     * Creates new form TLogin
     */
    public TLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_Esquerda = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        JP_Book = new javax.swing.JPanel();
        JL_Book = new javax.swing.JLabel();
        JP_Direita = new javax.swing.JPanel();
        JL_User = new javax.swing.JLabel();
        JL_Pasw = new javax.swing.JLabel();
        Btn_Entrar = new javax.swing.JButton();
        JTF_User = new javax.swing.JTextField();
        JPF_Pasw = new javax.swing.JPasswordField();
        JL_Esqueceu = new javax.swing.JLabel();
        JP_Sim = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        JP_Esquerda.setBackground(new java.awt.Color(25, 144, 115));
        JP_Esquerda.setMinimumSize(new java.awt.Dimension(300, 100));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        JP_Book.setBackground(new java.awt.Color(25, 144, 115));

        JL_Book.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_Book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8_saddle_stitched_booklet_90px_1.png"))); // NOI18N

        javax.swing.GroupLayout JP_BookLayout = new javax.swing.GroupLayout(JP_Book);
        JP_Book.setLayout(JP_BookLayout);
        JP_BookLayout.setHorizontalGroup(
            JP_BookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_BookLayout.createSequentialGroup()
                .addComponent(JL_Book, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JP_BookLayout.setVerticalGroup(
            JP_BookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JL_Book, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JP_EsquerdaLayout = new javax.swing.GroupLayout(JP_Esquerda);
        JP_Esquerda.setLayout(JP_EsquerdaLayout);
        JP_EsquerdaLayout.setHorizontalGroup(
            JP_EsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_EsquerdaLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(JP_EsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_EsquerdaLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_EsquerdaLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
            .addGroup(JP_EsquerdaLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(JP_Book, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JP_EsquerdaLayout.setVerticalGroup(
            JP_EsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_EsquerdaLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(JP_Book, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );

        getContentPane().add(JP_Esquerda, java.awt.BorderLayout.LINE_START);

        JP_Direita.setBackground(new java.awt.Color(255, 255, 255));

        JL_User.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JL_User.setText("USERNAME:");

        JL_Pasw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JL_Pasw.setText("PASSWORD:");

        Btn_Entrar.setBackground(new java.awt.Color(25, 144, 115));
        Btn_Entrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Btn_Entrar.setText("Entrar");
        Btn_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EntrarActionPerformed(evt);
            }
        });

        JPF_Pasw.setText("0000");
        JPF_Pasw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPF_PaswMouseClicked(evt);
            }
        });

        JL_Esqueceu.setBackground(new java.awt.Color(255, 255, 255));
        JL_Esqueceu.setText("Esqueceu os seus dados?");

        JP_Sim.setBackground(new java.awt.Color(255, 255, 255));
        JP_Sim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JP_SimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JP_SimMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Sim");

        javax.swing.GroupLayout JP_SimLayout = new javax.swing.GroupLayout(JP_Sim);
        JP_Sim.setLayout(JP_SimLayout);
        JP_SimLayout.setHorizontalGroup(
            JP_SimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_SimLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JP_SimLayout.setVerticalGroup(
            JP_SimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_SimLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout JP_DireitaLayout = new javax.swing.GroupLayout(JP_Direita);
        JP_Direita.setLayout(JP_DireitaLayout);
        JP_DireitaLayout.setHorizontalGroup(
            JP_DireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_DireitaLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(JP_DireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_DireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JL_Pasw)
                        .addComponent(JL_User))
                    .addComponent(Btn_Entrar))
                .addGroup(JP_DireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_DireitaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(JP_DireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTF_User)
                            .addComponent(JPF_Pasw, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addGap(153, 153, 153))
                    .addGroup(JP_DireitaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JL_Esqueceu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JP_Sim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        JP_DireitaLayout.setVerticalGroup(
            JP_DireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_DireitaLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(JP_DireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JL_User)
                    .addComponent(JTF_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(JP_DireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Pasw)
                    .addComponent(JPF_Pasw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(JP_DireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_Entrar)
                    .addGroup(JP_DireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JP_Sim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JL_Esqueceu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        getContentPane().add(JP_Direita, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JP_SimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_SimMouseEntered
        JP_Sim.setToolTipText("Fazer teste");
        JP_Sim.setBackground(new Color(25,144,115));
    }//GEN-LAST:event_JP_SimMouseEntered

    private void JP_SimMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_SimMouseExited
      JP_Sim.setBackground(Color.WHITE);
    }//GEN-LAST:event_JP_SimMouseExited

    private void JPF_PaswMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPF_PaswMouseClicked
        JPF_Pasw.setText("");
    }//GEN-LAST:event_JPF_PaswMouseClicked

    private void Btn_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EntrarActionPerformed
        TPrincipal principal = new TPrincipal();
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_Btn_EntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Entrar;
    private javax.swing.JLabel JL_Book;
    private javax.swing.JLabel JL_Esqueceu;
    private javax.swing.JLabel JL_Pasw;
    private javax.swing.JLabel JL_User;
    private javax.swing.JPasswordField JPF_Pasw;
    private javax.swing.JPanel JP_Book;
    private javax.swing.JPanel JP_Direita;
    private javax.swing.JPanel JP_Esquerda;
    private javax.swing.JPanel JP_Sim;
    private javax.swing.JTextField JTF_User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
