/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Smart Solution
 */
public class TPrincipal extends javax.swing.JFrame {
boolean a=true;
    /**
     * Creates new form TPrincipal
     */
    public TPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
    public void esconder(JPanel menu,boolean mostrar){
        if(mostrar==true)
            menu.setPreferredSize(new Dimension(40, menu.getHeight()));
        else
             menu.setPreferredSize(new Dimension(250, menu.getHeight()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_Superior = new javax.swing.JPanel();
        JP_Icones = new javax.swing.JPanel();
        JP_Max = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JP_Min = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JP_Exit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JP_Esquerda = new javax.swing.JPanel();
        JP_Esq_Icon = new javax.swing.JPanel();
        JP_HideMenu = new javax.swing.JPanel();
        JL_Esconder = new javax.swing.JLabel();
        Line1 = new javax.swing.JPanel();
        Line2 = new javax.swing.JPanel();
        JP_Inicio_Icon = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        JP_Sair_Icon = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        JP_Menu = new javax.swing.JPanel();
        JP_Inicio_Text = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        JP_Oficial = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        JP_Direita = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setUndecorated(true);

        JP_Superior.setBackground(new java.awt.Color(58, 114, 200));
        JP_Superior.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JP_Superior.setMinimumSize(new java.awt.Dimension(126, 50));
        JP_Superior.setPreferredSize(new java.awt.Dimension(886, 30));
        JP_Superior.setLayout(new java.awt.BorderLayout());

        JP_Icones.setBackground(new java.awt.Color(58, 114, 200));
        JP_Icones.setPreferredSize(new java.awt.Dimension(75, 20));
        JP_Icones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JP_Max.setBackground(new java.awt.Color(58, 114, 200));
        JP_Max.setPreferredSize(new java.awt.Dimension(20, 20));
        JP_Max.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JP_MaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JP_MaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JP_MaxMouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8_maximize_button_24px.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(19, 20));

        javax.swing.GroupLayout JP_MaxLayout = new javax.swing.GroupLayout(JP_Max);
        JP_Max.setLayout(JP_MaxLayout);
        JP_MaxLayout.setHorizontalGroup(
            JP_MaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_MaxLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        JP_MaxLayout.setVerticalGroup(
            JP_MaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_MaxLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        JP_Icones.add(JP_Max, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 20, 20));

        JP_Min.setBackground(new java.awt.Color(58, 114, 200));
        JP_Min.setPreferredSize(new java.awt.Dimension(20, 20));
        JP_Min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JP_MinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JP_MinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JP_MinMouseExited(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8_horizontal_line_26px.png"))); // NOI18N

        javax.swing.GroupLayout JP_MinLayout = new javax.swing.GroupLayout(JP_Min);
        JP_Min.setLayout(JP_MinLayout);
        JP_MinLayout.setHorizontalGroup(
            JP_MinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_MinLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
        );
        JP_MinLayout.setVerticalGroup(
            JP_MinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_MinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, Short.MAX_VALUE)
                .addContainerGap())
        );

        JP_Icones.add(JP_Min, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, -1));

        JP_Exit.setBackground(new java.awt.Color(58, 114, 200));
        JP_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JP_ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JP_ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JP_ExitMouseExited(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8_delete_50px_1.png"))); // NOI18N

        javax.swing.GroupLayout JP_ExitLayout = new javax.swing.GroupLayout(JP_Exit);
        JP_Exit.setLayout(JP_ExitLayout);
        JP_ExitLayout.setHorizontalGroup(
            JP_ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, Short.MAX_VALUE)
        );
        JP_ExitLayout.setVerticalGroup(
            JP_ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_ExitLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        JP_Icones.add(JP_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 20));

        JP_Superior.add(JP_Icones, java.awt.BorderLayout.LINE_END);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Tela Principal");
        JP_Superior.add(jLabel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(JP_Superior, java.awt.BorderLayout.PAGE_START);

        JP_Esquerda.setBackground(new java.awt.Color(204, 204, 204));
        JP_Esquerda.setPreferredSize(new java.awt.Dimension(250, 480));
        JP_Esquerda.setLayout(new java.awt.BorderLayout());

        JP_Esq_Icon.setBackground(new java.awt.Color(97, 114, 131));
        JP_Esq_Icon.setPreferredSize(new java.awt.Dimension(40, 608));
        JP_Esq_Icon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JP_HideMenu.setBackground(new java.awt.Color(97, 114, 131));
        JP_HideMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JP_HideMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JP_HideMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JP_HideMenuMouseExited(evt);
            }
        });
        JP_HideMenu.setLayout(new java.awt.BorderLayout());

        JL_Esconder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_Esconder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8_back_30px.png"))); // NOI18N
        JP_HideMenu.add(JL_Esconder, java.awt.BorderLayout.PAGE_END);

        JP_Esq_Icon.add(JP_HideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, 32));

        Line1.setBackground(new java.awt.Color(97, 114, 131));
        Line1.setPreferredSize(new java.awt.Dimension(40, 5));

        javax.swing.GroupLayout Line1Layout = new javax.swing.GroupLayout(Line1);
        Line1.setLayout(Line1Layout);
        Line1Layout.setHorizontalGroup(
            Line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        Line1Layout.setVerticalGroup(
            Line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        JP_Esq_Icon.add(Line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 10));

        Line2.setBackground(new java.awt.Color(97, 114, 131));
        Line2.setPreferredSize(new java.awt.Dimension(40, 5));

        javax.swing.GroupLayout Line2Layout = new javax.swing.GroupLayout(Line2);
        Line2.setLayout(Line2Layout);
        Line2Layout.setHorizontalGroup(
            Line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        Line2Layout.setVerticalGroup(
            Line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        JP_Esq_Icon.add(Line2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 40, 10));

        JP_Inicio_Icon.setBackground(new java.awt.Color(97, 114, 131));
        JP_Inicio_Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JP_Inicio_IconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JP_Inicio_IconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JP_Inicio_IconMouseExited(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8_home_32px.png"))); // NOI18N

        javax.swing.GroupLayout JP_Inicio_IconLayout = new javax.swing.GroupLayout(JP_Inicio_Icon);
        JP_Inicio_Icon.setLayout(JP_Inicio_IconLayout);
        JP_Inicio_IconLayout.setHorizontalGroup(
            JP_Inicio_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_Inicio_IconLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JP_Inicio_IconLayout.setVerticalGroup(
            JP_Inicio_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        JP_Esq_Icon.add(JP_Inicio_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 40, -1));

        JP_Sair_Icon.setBackground(new java.awt.Color(97, 114, 131));
        JP_Sair_Icon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8_shutdown_30px.png"))); // NOI18N
        JP_Sair_Icon.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        JP_Esq_Icon.add(JP_Sair_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 40, 40));

        JP_Esquerda.add(JP_Esq_Icon, java.awt.BorderLayout.LINE_START);

        JP_Menu.setBackground(new java.awt.Color(221, 220, 220));
        JP_Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JP_Inicio_Text.setBackground(new java.awt.Color(221, 220, 220));
        JP_Inicio_Text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JP_Inicio_TextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JP_Inicio_TextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JP_Inicio_TextMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setText("Início ");

        javax.swing.GroupLayout JP_Inicio_TextLayout = new javax.swing.GroupLayout(JP_Inicio_Text);
        JP_Inicio_Text.setLayout(JP_Inicio_TextLayout);
        JP_Inicio_TextLayout.setHorizontalGroup(
            JP_Inicio_TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_Inicio_TextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        JP_Inicio_TextLayout.setVerticalGroup(
            JP_Inicio_TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_Inicio_TextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JP_Menu.add(JP_Inicio_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 210, 40));

        JP_Oficial.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setText("Início ");

        javax.swing.GroupLayout JP_OficialLayout = new javax.swing.GroupLayout(JP_Oficial);
        JP_Oficial.setLayout(JP_OficialLayout);
        JP_OficialLayout.setHorizontalGroup(
            JP_OficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_OficialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        JP_OficialLayout.setVerticalGroup(
            JP_OficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_OficialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        JP_Menu.add(JP_Oficial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JP_Esquerda.add(JP_Menu, java.awt.BorderLayout.CENTER);

        getContentPane().add(JP_Esquerda, java.awt.BorderLayout.LINE_START);

        JP_Direita.setBackground(new java.awt.Color(255, 255, 255));
        JP_Direita.setLayout(new java.awt.BorderLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/maxresdefault.jpg"))); // NOI18N
        JP_Direita.add(jLabel8, java.awt.BorderLayout.CENTER);

        getContentPane().add(JP_Direita, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(886, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JP_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_ExitMouseClicked
       System.exit(0);
    }//GEN-LAST:event_JP_ExitMouseClicked

    private void JP_ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_ExitMouseEntered
      JP_Exit.setBackground(new Color(97,114,131));
    }//GEN-LAST:event_JP_ExitMouseEntered

    private void JP_ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_ExitMouseExited
       JP_Exit.setBackground(new Color(58,114,200));
    }//GEN-LAST:event_JP_ExitMouseExited

    private void JP_MaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_MaxMouseClicked
        if(this.getExtendedState()!=TPrincipal.MAXIMIZED_BOTH)
            this.setExtendedState(TPrincipal.MAXIMIZED_BOTH);
        else
            this.setExtendedState(TPrincipal.NORMAL);
    }//GEN-LAST:event_JP_MaxMouseClicked

    private void JP_MaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_MaxMouseEntered
        JP_Max.setBackground(new Color(97,114,131));
    }//GEN-LAST:event_JP_MaxMouseEntered

    private void JP_MaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_MaxMouseExited
         JP_Max.setBackground(new Color(58,114,200));
    }//GEN-LAST:event_JP_MaxMouseExited

    private void JP_MinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_MinMouseClicked
       this.setExtendedState(TPrincipal.ICONIFIED);
    }//GEN-LAST:event_JP_MinMouseClicked

    private void JP_MinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_MinMouseEntered
       
        JP_Min.setBackground(new Color(97,114,131));
    }//GEN-LAST:event_JP_MinMouseEntered

    private void JP_MinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_MinMouseExited
     JP_Min.setBackground(new Color(58,114,200));
    }//GEN-LAST:event_JP_MinMouseExited

    private void JP_HideMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_HideMenuMouseClicked
        if(a==true){
            esconder(JP_Esquerda, a);
             JL_Esconder.setIcon(new ImageIcon(getClass().getResource("/Icones/icons8_list_24px.png")));
            SwingUtilities.updateComponentTreeUI(this);
            a=false;
        }
        else{
           
            esconder(JP_Esquerda, a);
             JL_Esconder.setIcon(new ImageIcon(getClass().getResource("/Icones/icons8_back_30px.png")));
            SwingUtilities.updateComponentTreeUI(this);
            a=true;
        }
    }//GEN-LAST:event_JP_HideMenuMouseClicked

    private void JP_HideMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_HideMenuMouseEntered
    JP_HideMenu.setBackground(new Color(58,114,200));
    Line1.setBackground(Color.white);
    Line2.setBackground(Color.white);
    if(a==true)
           JP_HideMenu.setToolTipText("Fechar");
       else
           JP_HideMenu.setToolTipText("Abrir");
    }//GEN-LAST:event_JP_HideMenuMouseEntered

    private void JP_HideMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_HideMenuMouseExited
       
        JP_HideMenu.setBackground(new Color(97,114,131));
        Line1.setBackground(new Color(97,114,131));
        Line2.setBackground(new Color(97,114,131));
        
    }//GEN-LAST:event_JP_HideMenuMouseExited

    private void JP_Inicio_TextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_Inicio_TextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JP_Inicio_TextMouseClicked

    private void JP_Inicio_TextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_Inicio_TextMouseEntered
       JP_Inicio_Text.setBackground(new Color(8,114,200));
       JP_Inicio_Icon.setBackground(new Color(58,114,200));
    }//GEN-LAST:event_JP_Inicio_TextMouseEntered

    private void JP_Inicio_TextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_Inicio_TextMouseExited
       JP_Inicio_Icon.setBackground(new Color(97,114,131));
       JP_Inicio_Text.setBackground(new Color(221,220,220));
    }//GEN-LAST:event_JP_Inicio_TextMouseExited

    private void JP_Inicio_IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_Inicio_IconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JP_Inicio_IconMouseClicked

    private void JP_Inicio_IconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_Inicio_IconMouseEntered
        JP_Inicio_Text.setBackground(new Color(8,114,200));
       JP_Inicio_Icon.setBackground(new Color(58,114,200));
    }//GEN-LAST:event_JP_Inicio_IconMouseEntered

    private void JP_Inicio_IconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_Inicio_IconMouseExited
      JP_Inicio_Icon.setBackground(new Color(97,114,131));
       JP_Inicio_Text.setBackground(new Color(221,220,220));
    }//GEN-LAST:event_JP_Inicio_IconMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_Esconder;
    private javax.swing.JPanel JP_Direita;
    private javax.swing.JPanel JP_Esq_Icon;
    private javax.swing.JPanel JP_Esquerda;
    private javax.swing.JPanel JP_Exit;
    private javax.swing.JPanel JP_HideMenu;
    private javax.swing.JPanel JP_Icones;
    private javax.swing.JPanel JP_Inicio_Icon;
    private javax.swing.JPanel JP_Inicio_Text;
    private javax.swing.JPanel JP_Max;
    private javax.swing.JPanel JP_Menu;
    private javax.swing.JPanel JP_Min;
    private javax.swing.JPanel JP_Oficial;
    private javax.swing.JPanel JP_Sair_Icon;
    private javax.swing.JPanel JP_Superior;
    private javax.swing.JPanel Line1;
    private javax.swing.JPanel Line2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
